language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER planter;' -U postgres
  - psql -c 'CREATE DATABASE planter OWNER planter;' -U postgres

script:
  - go fmt ./...
  - go test -v
